---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install distro packages
  package:
    name: "{{ glance_distro_packages }}"
    state: "{{ glance_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr in ['apt', 'zypper']) | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in glance_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: glance_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ glance_requires_pip_packages }}"
    state: "{{ glance_pip_package_state }}"
    extra_args: >-
      {{ glance_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Retrieve checksum for venv download
  uri:
    url: "{{ glance_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: glance_venv_checksum
  when: glance_venv_download | bool

- name: Attempt venv download
  get_url:
    url: "{{ glance_venv_download_url }}"
    dest: "/var/cache/{{ glance_venv_download_url | basename }}"
    checksum: "sha1:{{ glance_venv_checksum.content | trim }}"
  register: glance_get_venv
  when: glance_venv_download | bool

- name: Remove existing venv
  file:
    path: "{{ glance_bin | dirname }}"
    state: absent
  when: glance_get_venv | changed

- name: Create glance venv dir
  file:
    path: "{{ glance_bin | dirname }}"
    state: directory
  register: glance_venv_dir
  when: glance_get_venv | changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ glance_venv_download_url | basename }}"
    dest: "{{ glance_bin | dirname }}"
    copy: "no"
  when: glance_get_venv | changed
  notify:
    - Restart glance services

- name: Install pip packages
  pip:
    name: "{{ glance_pip_packages }}"
    state: "{{ glance_pip_package_state }}"
    virtualenv: "{{ glance_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ glance_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when: glance_get_venv | failed or glance_get_venv | skipped
  notify:
    - Restart glance services

- name: Remove python from path first (CentOS, openSUSE)
  file:
    path:  "{{ glance_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']
    - glance_get_venv | changed

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto --reinitialize {{ glance_bin | dirname }}
  when: glance_get_venv | changed

- name: Record the need for a service restart
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: glance
    option: need_service_restart
    value: True
  when: (glance_get_venv | changed) or
        (glance_venv_dir | changed) or
        (install_packages | changed) or
        (ansible_local is not defined) or
        ('openstack_ansible' not in ansible_local) or
        ('glance' not in ansible_local['openstack_ansible']) or
        ('need_service_restart' not in ansible_local['openstack_ansible']['glance'])

- name: Record the venv tag deployed
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: glance
    option: venv_tag
    value: "{{ glance_venv_tag }}"
